
add_newline = true

[directory]
truncation_length = 20 # Show max 20 directories
truncate_to_repo = true # if in a git repo trucate path to here

[aws]
disabled = true

[conda]
ignore_base = false

[kubernetes]
disabled = true
format = '[$context \($namespace\)](dimmed green) '
